version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "5455:5432"
